### ISSUE TITLE
Update example to react native 0.60.0+

### ISSUE THREAD

**Issue by jorgemasta** [Woonivers/react-native-document-scanner#18]

**Comment by haneul512** [comment]
hello @jorgemarrero 
Still having trouble running the example code for RN 0.60.0.
I have followed instructions from readme, but I get 

error: cannot find symbol
import org.opencv.DocumentScannerPackage;

when I try to build for Android. Any ideas?

**Comment by jorgemasta** [comment]
> hello @jorgemarrero
> Still having trouble running the example code for RN 0.60.0.
> I have followed instructions from readme, but I get
> 
> error: cannot find symbol
> import org.opencv.DocumentScannerPackage;
> 
> when I try to build for Android. Any ideas?

Thanks for reporting @haneul512 . Yes, it's a problem related to the auto-linking

It has been resolved. I forgot to add the file `react-native.config.js` to npm, it is published in version 2.0.1.

I have also modified the `package.json` in the example so that it points directly to the root folder, not to npm.

**Fresh install and try again** 💪

**Comment by haneul512** [comment]
> **Fresh install and try again** 💪

It works now! thanks mate.  I owe you a beer 🍺🍺🍺🍺
