### ISSUE TITLE
com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed

### ISSUE THREAD

**Issue by minh-dai** [Woonivers/react-native-document-scanner#30]
Android: gradle release build fails in verifyReleaseResources step.
Execution failed for task ':@woonivers_react-native-document-scanner:verifyReleaseResources'.
> 1 exception was raised by workers:
  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed

  /Users/tranthaixoan/Desktop/RN/OrbitPrime/node_modules/@woonivers/react-native-document-scanner/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.

  error: failed linking references.

How to reproduce :
cd android
./gradlew assembleRelease

**Comment by waldobeest** [comment]
I have made a PR for this. https://github.com/Woonivers/react-native-document-scanner/pull/31
